AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  FromEmail:
    Type: String
    Default: 'your@email.com'
    Description: (Required) Represents the email sender. Must be a SES verified email. If you attempt to send email using a non-verified address or domain, the operation results in an "Email address not verified" error. Minimum 4 characters.
    MinLength: 4
    MaxLength: 70
    ConstraintDescription: 'Required. Must be a SES verified email address.'
  TemplateName:
    Type: String
    Description: (Required) The Name of the Email Template you want to use.
    MinLength: 2
    MaxLength: 70
    ConstraintDescription: 'Required. In order to send a Templated Email, you need to specify an existing email template name. Otherwise it result in an operation error.'
  CorsOrigin:
    Type: String
    Default: ''
    Description: (Optional) Cross-origin resource sharing (CORS) Origin. You can specify a single origin, all "*" or leave empty and no CORS will be applied.
    MaxLength: 250
Conditions:
  IsCorsDefined: !Not [!Equals [!Ref CorsOrigin, '']]
Resources:
  LambdaTemplatedEmailer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          FROM_EMAIL: !Ref FromEmail
          CORS_ORIGIN: !Ref CorsOrigin
          TEMPLATE_NAME: !Ref TemplateName
      Policies:
        - SESCrudPolicy:
            IdentityName: !Ref FromEmail
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendTemplatedEmail
            Resource: "*"
      Events:
        TemplatedEmailApi:
          Type: Api
          Properties:
            Path: /send-template
            Method: POST
        TemplatedEmailOptionsApi:
          Type: Api
          Properties:
            Path: /send-template
            Method: OPTIONS
Outputs:
  ApiUrl:
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/send-template
    Description: The URL of the API Gateway you should invoke to send a templated email